general:
  output_folder: ../videos/outputs/
  draw_classification: false
  draw_statistics_text: false
  draw_statistics_graphics: false
  draw_panel_faces: false
  inference_period: 1

video:
  input_top: 0
  input_left: 0
  input_width: 0
  input_height: 0

mobilenetv2:
  # detection_threshold: 0.5
  # nms_threshold: 0.1
  # distance_threshold: 1
  tf_trt_graph: ../mobilenetv2/converted_trt_708_400_bs1.pb
  batch_size: 1

yolo_generic:
  detection_threshold: 0.5
  nms_threshold: 0.1
  distance_threshold: 1
  yolo_variant: "yolo_darknet_tiny"  # One of the configurations below

yolo_darknet:  # Config specific to original darknet implementation (detector_darknet.py)
  darknet_path: ../yolo/  # Path with libdarknet.so
  config_file: ../yolo/facemask-yolov4.cfg
  data_file: integrations/yolo/obj.data
  weights_file: ../yolo/facemask-yolov4_best.weights

yolo_darknet_tiny:
  darknet_path: ../yolo/  # Path with libdarknet.so
  config_file: ../yolo/facemask-yolov4-tiny.cfg
  data_file: integrations/yolo/obj.data
  weights_file: ../yolo/facemask-yolov4-tiny_best.weights

yolo_pytorch:
  repo_path: ../yolo/pytorch-YOLOv4
  config_file: ./integrations/yolo/yolov4-facemask.cfg
  names_file: ./integrations/yolo/obj.names
  weights_file: ./yolov4-facemask_best.weights
  use_cuda: true

yolo_trt:
  names_file: ../yolo/data/obj.names
  engine_file: ../../yolo/tensorrt_yolo.trt
  use_cuda: true
  input_width: 608
  input_height: 608
  batch_size: 1

yolo_trt_tiny:
  names_file: ../yolo/data/obj.names
  # engine_file: ../yolo/yolov4-facemask-tiny-fp16.trt
  # engine_file: ../../tensorrt_1024_608_fp16.trt
  engine_file: ../../tensorrt_batch8_fp16.trt
  use_cuda: true
  input_width: 608
  input_height: 608
  batch_size: 8

face_mask_detector:
  threshold_vote: 0.8
  extract_faces_step: 5
  face_min_size: 32
  classification_batch: 10
  classification_voting: true
  box_no_mask: true
  stat_box_side: "right"
  resolution: "4k"  # could be "hd" or nothing
  classification_max_votes: 100

  # Default params
  left_margin: 0
  right_margin: 0
  top_margin: 0
  bottom_margin: 0


debug:
  tracker_enabled: false
  facemask_enabled: false
  output_detector_resolution: true
  draw_detections: true
  draw_tracking_ids: false
  draw_tracking_debug: false
  draw_predictions: false
  draw_face_boxes: false
  profiler: true
